{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/blinqsdk\/traceerror\/errordescription-31yo5"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError\/errorDescription-31yo5","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"role":"symbol","title":"errorDescription","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"symbolKind":"property","externalID":"s:10Foundation14LocalizedErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:8BlinqSDK10TraceErrorO","extendedModule":"Foundation","modules":[{"name":"BlinqSDK"}]},"hierarchy":{"paths":[["doc:\/\/BlinqSDK\/documentation\/BlinqSDK","doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError","doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError\/LocalizedError-Implementations"]]},"references":{"doc://BlinqSDK/documentation/BlinqSDK/TraceError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/blinqsdk\/traceerror\/localizederror-implementations"},"doc://BlinqSDK/documentation/BlinqSDK/TraceError/errorDescription-31yo5":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError\/errorDescription-31yo5","kind":"symbol","type":"topic","url":"\/documentation\/blinqsdk\/traceerror\/errordescription-31yo5"},"doc://BlinqSDK/documentation/BlinqSDK":{"role":"collection","title":"BlinqSDK","abstract":[],"identifier":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK","kind":"symbol","type":"topic","url":"\/documentation\/blinqsdk"},"doc://BlinqSDK/documentation/BlinqSDK/TraceError":{"role":"symbol","title":"TraceError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TraceError"}],"abstract":[{"type":"codeVoice","code":"TraceError"},{"type":"text","text":" defines a set of errors that can occur while handling traces."}],"identifier":"doc:\/\/BlinqSDK\/documentation\/BlinqSDK\/TraceError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TraceError"}],"url":"\/documentation\/blinqsdk\/traceerror"}}}